ARG RUBY_VERSION=3.2.6

FROM ubuntu:22.04 AS base

ENV LANG=C.UTF-8

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      curl git build-essential libpq-dev libssl-dev zlib1g-dev \
      libreadline-dev libffi-dev libyaml-dev autoconf bison \
      libgdbm-dev libncurses5-dev libtool pkg-config \
      libxrender1 libxext6 libfontconfig1 libpng16-16 libfreetype6 \
      xfonts-base xfonts-75dpi \
      ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ARG RUBY_VERSION

RUN git clone https://github.com/rbenv/ruby-build.git /usr/local/src/ruby-build && \
    cd /usr/local/src/ruby-build && ./install.sh && \
    ruby-build "$RUBY_VERSION" /usr/local

ENV PATH="/usr/local/bin:$PATH"

RUN ruby -v && gem install bundler --no-document

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

RUN bundle exec rails tailwindcss:build

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

CMD bin/rails db:migrate && \
    bin/rails db:fixtures:load && \
    bin/rails server -b 0.0.0.0
